### ISSUE TITLE
Configure Notifications while Printing

### ISSUE THREAD

**Issue by Schwuuuuup** [ksergey/klipper-tg-bot#4]
Hi,

is there a way to disable or configure the progress notifications. Basically I just want "started" and "conpleted" or "error". "Printing 80%" "printing 90%" "printing 95" is a bit much for my taste

**Comment by ksergey** [comment]
Hi!

Please update to 0.1.2b and modify your config:
```ini
[moonraker]
....
notification_events = state
```

Thanks

**Comment by ksergey** [comment]
fixed 0.1.2b
